# Generated by Django 4.0.6 on 2022-07-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_token',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
